### ISSUE TITLE
Undefined sysmbol in logprob.so

### ISSUE THREAD

**Issue by cflsjt** [EhsanMotazedi/PopPoly#1]
Hi @EhsanMotazedi - I'm finally getting a chance to play with your latest tool! I ran in to an issue though, maybe no biggie. I've git cloned recursively but upon running:

```python main.py -h```

I get this output    
```Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from branchprune import BlockException, makePermutation, SetGenos, GetProbReads
  File "/powerplant/workspace/cflsjt/PopPoly/branchprune.py", line 13, in <module>
    from haplotypes import Haplotypes, getMEC
  File "/powerplant/workspace/cflsjt/PopPoly/haplotypes.py", line 12, in <module>
    from logprob import _xor, diffVec, Hamming
ImportError: /powerplant/workspace/cflsjt/PopPoly/logprob.so: undefined symbol: PyFPE_jbuf ```

**Comment by EhsanMotazedi** [comment]
HI Susan,

This error has indeed been reported by other users (including myself!). It
has to do with numpy installation and I get it on one server while not not
another. I have uploaded a new version of PopPoly in which I mention this
error and give a link where it is discussed on StackOverflow. In the new
version, one can explicitly specify the name of the parents. There is also
a perl wrapper with extra options to use a bam file that contains multiple
contigs by choosing the name of the desired contig for haplotyping, as well
as to filtering SNPs upon genotype missing rate. Please have a look:

https://git.wageningenur.nl/motaz001/PopPoly

Cheers,
Ehsan

Op wo 18 jul. 2018 om 06:52 schreef Susan Thomson <notifications@github.com

**Comment by cflsjt** [comment]
Hi Ehsan, thanks yes it looks like numpy. I'm still having some issues but we will try and set up a clean conda env to have a go with shortly. Let you know how it goes!

**Comment by timothymillar** [comment]
Hi @EhsanMotazedi I think [this issue](https://github.com/numpy/numpy/issues/8415#issuecomment-269103493) explains it. 

It looks like the version(s) of CPython available through anaconda are compiled without the `--with-fpectl`. 

The pre-compiled `logprob.so` and `logprob2.so` must have been compiled againt a version of CPython that does support `fpectl` (e.g the versions packaged in Ubuntu/Debian).

I remove `logprob.so` and `logprob2.so` and rebuilt them against Anacondas python and now the I can get the help text without issue.

**Comment by EhsanMotazedi** [comment]
@timothymillar Hi Timo, You are right just have to recompile using cythonize -i logprob.pyx and cythonize -i logprob2.pyx. Hope it works!
