### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by cflsjt** [EhsanMotazedi/PopPoly#2]
Hi @EhsanMotazedi sorry but now I'm getting this error message. We (as in Tim) will take a look, have you come across this issue??

**Comment by cflsjt** [comment]
@EhsanMotazedi not getting anywhere with this issue. I'm trying on my local machine - oSX but I'm back to have logprob issues, same error whether I use the latest git version from your repo or the one that @timothymillar has recompiled. I'm not having any luck testing popPoly :( 

  ```
Traceback (most recent call last):
  File "./main.py", line 18, in <module>
    from branchprune import BlockException, makePermutation, SetGenos, GetProbReads
  File "/Users/cflsjt/Workspace/PopPoly/branchprune.py", line 13, in <module>
    from haplotypes import Haplotypes, getMEC
  File "/Users/cflsjt/Workspace/PopPoly/haplotypes.py", line 12, in <module>
    from logprob import _xor, diffVec, Hamming
ImportError: dlopen(/Users/cflsjt/Workspace/PopPoly/logprob.so, 2): no suitable image found.  Did find:
	/Users/cflsjt/Workspace/PopPoly/logprob.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/cflsjt/Workspace/PopPoly/logprob.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

**Comment by EhsanMotazedi** [comment]
Hi Susan,
Sorry to hear that:-(. This error is usually caused when the given path to
the bam or to the vcf file is note correct. Maybe you could send me two
small bam and vcf files that cause the error, as well as the command used,
so that I can try it?

Cheers, ehsan

**Comment by cflsjt** [comment]
@EhsanMotazedi I got that from trying a local implementation, just testing with the -h flag. Are there any specifics about your environment we can check in ours?

**Comment by cflsjt** [comment]
@EhsanMotazedi interesting dev...running on our head node at commandline rather than through notebook - might have success....so is a jupyter thing maybe!

**Comment by EhsanMotazedi** [comment]
@cflsjt Hi Susan, a bit late but just that I got the same error after I updated my OS! Just use cythonize -i logprob.pyx and cythonize -i logprob2.pyx to recompile these modules and it should work!
